global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'student-monitoring'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node'
    static_configs:
      - targets: ['node_exporter:9100']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'my_laptop'

  - job_name: 'postgresql'
    static_configs:
      - targets: ['postgres_exporter:9187']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'my_postgresql_db'

  - job_name: 'weather_exporter'
    static_configs:
      - targets: ['host.docker.internal:8000']  # или 'localhost:8000', если exporter крутится внутри контейнера
    scrape_interval: 20s
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'external_apis'
